---
- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 拷贝nginx,keepalived安装包
  unarchive: src={{ software_dir }}/ha.tar.gz dest={{ tmp_dir }}

- name: 安装keepalived高可用软件
  shell: rpm -ivh {{ tmp_dir }}/{{ item }}
  with_items:
    - "net-snmp-libs-5.7.2-49.el7.x86_64.rpm"
    - "lm_sensors-libs-3.4.0.el7.x86_64.rpm"
    - "net-snmp-agent-libs-5.7.2-49.el7.x86_64.rpm"
    - "keepalived-1.3.5-19.el7.x86_64.rpm"
  register: result
  failed_when: "'已经安装' in result['stdout']"

- name: 安装nginx
  shell: rpm -ivh {{ tmp_dir }}/nginx-1.18.0-1.el7.ngx.x86_64.rpm
  register: result
  failed_when: "'已经安装' in result['stdout']"

- name: 拷贝nginx配置文件
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: 拷贝keepalived配置文件       
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: 拷贝nginx健康检查脚本
  copy: src=check_nginx.sh dest=/etc/keepalived/ mode=u+x

- name: 启动服务
  systemd: name={{ item }} state=restarted enabled=yes daemon_reload=yes
  with_items:
    - nginx
    - keepalived
