# system initialization tasks for all nodes
- name: 系统初始化
  gather_facts: false
  hosts: all 
  roles:
    - sysinit

# to install a container runtime
- name: 部署容器运行时
  gather_facts: false
  hosts: k8s 
  roles:
    - containerd

# to set up 'kube_node' nodes
- name: 部署K8S Worker节点
  gather_facts: false
  hosts: k8s 
  roles:
    - kube-node
